spring:
  datasource:
    url: jdbc:mysql://47.113.110.213:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  data:
    mongodb:
      host: 47.113.110.213
      port: 27017
      database: mall-port
  redis:
    host: 47.113.110.213 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: 47.113.110.213
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
# 日志配置
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: 47.113.110.213