spring:
  datasource:
    url: jdbc:mysql://47.113.110.213:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: 47.113.110.213